In [1]:
import numpy as np

In [27]:
# For 2 variables
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)
        self.weights = 2*np.random.random((3,1))-1
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    def sigmoidDerivative(self,x):
        return x*(1-x)
    def train(self,training_inputs,training_outputs,training_iterations):
        for itr in range(training_iterations):
            output = self.think(training_inputs)
            error = training_outputs-output
            adjustments = np.dot(training_inputs.T,error*self.sigmoidDerivative(output))
            self.weights += adjustments
    def think(self,inputs):
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs,self.weights))
        return output
    
if __name__ == '__main__':
    nn = NeuralNetwork()
    print('Randomly Generating Weights')
    print(nn.weights)
    trainingInputs = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
    trainingOutput = np.array([[0,1,1,0]]).T
    nn.train(trainingInputs,trainingOutput,40)
    print('Weights After Training: ')
    print(nn.weights)
    input1 = str(input('Enter Input 1: \t'))
    input2 = str(input('Enter Input 2: \t'))
    input3 = str(input('Enter Input 3: \t'))
    print(f'With Inputs Values {input1} , {input2} , {input3}')
    print('New Output Data:')
    print(nn.think(np.array([input1,input2,input3])))

Randomly Generating Weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weights After Training: 
[[ 0.05075967]
 [ 0.11553821]
 [-0.09714324]]
Enter Input 1: 	1
Enter Input 2: 	1
Enter Input 3: 	1
With Inputs Values 1 , 1 , 1
New Output Data:
[0.51728177]


In [25]:
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)
        self.weights = 2*np.random.random((4,1))-1
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    def sigmoidDerivative(self,x):
        return x*(1-x)
    def train(self,training_inputs,training_outputs,training_iterations):
        for itr in range(training_iterations):
            output = self.think(training_inputs)
            error = training_outputs-output
            adjustments = np.dot(training_inputs.T,error*self.sigmoidDerivative(output))
            self.weights += adjustments
    def think(self,inputs):
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs,self.weights))
        return output
    
if __name__ == '__main__':
    nn = NeuralNetwork()
    print('Randomly Generating Weights')
    print(nn.weights)
    trainingInputs = np.array([[0,0,0,1],
                               [0,0,1,1],
                               [0,1,0,1],
                               [0,1,1,1],
                               [1,0,0,1],
                               [1,0,1,1],
                               [1,1,0,1],
                               [1,1,1,1]])
    trainingOutput = np.array([[0,1,1,0,1,0,0,1]]).T
    nn.train(trainingInputs,trainingOutput,200)
    print('Weights After Training: ')
    print(nn.weights)
    input1 = str(input('Enter Input 1: \t'))
    input2 = str(input('Enter Input 2: \t'))
    input3 = str(input('Enter Input 3: \t'))
    input4 = str(input('Enter Input 4: \t'))
    print(f'With Inputs Values {input1} , {input2} , {input3} , {input4}')
    print('New Output Data:')
    print(nn.think(np.array([input1,input2,input3,input4])))

Randomly Generating Weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]
 [-0.39533485]]
Weights After Training: 
[[ 2.88238853e-08]
 [ 2.88250223e-08]
 [ 2.88202214e-08]
 [-4.99229749e-08]]
Enter Input 1: 	1
Enter Input 2: 	1
Enter Input 3: 	1
Enter Input 4: 	1
With Inputs Values 1 , 1 , 1 , 1
New Output Data:
[0.50000001]
